theme: minima
title: Budding Webdesigner
author: D
email: dbrummett@showimanging.com
description: > # this means to ignore newlines until "baseurl:"
  Cronicalling the journey from webdesign ignorant to passiably functional.

# social links
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
